### ISSUE TITLE
Spinnaker deployment in GCP Marketplace stuck

### ISSUE THREAD

**Issue by cocho-gore** [GoogleCloudPlatform/spinnaker-for-gcp#133]
The deployment available in Marketplace can't successfully ends. I tried several times and in the most of the times the pods and jobs stay stuck in Pending creation, Does not have minimum availability - crashloopback,  FailedCreatePodSandbox, PVC unbound.
e.g.

Failed create pod sandbox: rpc error: code = Unknown desc = Error response from daemon: Get https://k8s.gcr.io/v2/: dial tcp: lookup k8s.gcr.io on 169.254.169.254:53: no such host

From the workload:

- Pod  spin-gate : Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.fetch
-Pod  spin-cloud driver:   Could not get a resource from the pool at redis.clients.util.Pool.getResource(Pool.java:53) ~[jedis-2.9.3.jar:na] at redis.clients.jedis.JedisPool.getResource(JedisPool.java:226) ~[jedis-2.9.3.jar:na] at
-Pod spin-Kayenta :  Error creating bean with name 'atlasQueueMonitor' defined in URL [jar:file:/opt/kayenta/lib/orca-queue-6.139.0.jar!/com/netflix/spinnaker/orca/q/metrics/AtlasQueueMonitor.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'queue' defined in class path resource
- Pod Spin Ocra : Error creating bean with name 'defaultExecutionPromoter' defined in URL [jar:file:/opt/orca/lib/orca-qos.jar!/com/netflix/spinnaker/orca/qos/DefaultExecutionPromoter.class]: Unsatisfied dependency expressed through constructor parameter 0; 
- Pod  Spin-ocra: redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.util.Pool.getResource(Pool.java:53) ~[jedis-2.9.0.jar:na]
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:226) ~[jedis-2.9.0.jar:na]

Scaling up doesn't solve the issue, after several attempts to deploy the solution always goes to one status above listed

Can you help to know what is happening? 

I have the hypothesis that the issue could be related to image version used but is just a but it's just a guess. 

Additional in some cases the pod stuck in a restart loop due to the readiness probe failed 

Readiness probe failed: wget can't connect to remote host (127.0.0.1) : connection refused

Any insight would be appreciate.

**Comment by demobox** [comment]
Thanks for reporting this! Did you install Spinnaker into a new cluster, or one you had already created?

Also, do you know if your organization has policy constraints in place that restrict what's possible in your GCP projects? We've seen this cause a few issues for other users, hence the question.

**Comment by cocho-gore** [comment]
Hi!!

I installed in a new cluster, about the organization policies, as far as I Know we don't have any. The weekend I was trying this deployment again and I was able to deploy successfully the Spinnaker changing the version in the properties file before running the setup.sh, the version used is the 1.24.0. I deployed this around 4 -5 times successfully but when I tried the 1.23.2 I get the same status "Pods are pending" and once  the "does not have minimum availability".

**Comment by demobox** [comment]
> the version used is the 1.24.0. I deployed this around 4 -5 times successfully but when I tried the 1.23.2 I get the same status "Pods are pending" and once the "does not have minimum availability"

Ah, interesting - so it looks like the version may be the issue here. Are you able to use 1.24.0 or do you need to use the (problematic) 1.23.2 version?

Thanks for the additional details!

**Comment by cocho-gore** [comment]
Hi!

The 1.24.0 is good for now, but would be great if you can fix the 1.23.2 since the marketplace solution by default route you to the 1.23.2 or to fix the deployment to allow the user choose the version.

Thanks in advanced.

**Comment by demobox** [comment]
> The 1.24.0 is good for now

Glad to hear! Agree that we obviously want to make sure that the default version works too.

/cc @duftler on that

**Comment by cocho-gore** [comment]
Hi again!!
thanks for take a look, also I'm experiencing some issue regarding expose publicly, it seems like the script to expose through external IP doesn't create the resources preventing to connect to Spinnaker
Could you also check this ?

thanks in advance.

**Comment by demobox** [comment]
> it seems like the script to expose through external IP doesn't create the resources preventing to connect to Spinnaker

It sounds like this is a separate question - could you kindly open a new issue for that? And could you provide a few more details on the problem: is the problem that you *can*, or *cannot*, connect to Spinnaker after running the command to expose Spinnaker publicly?

**Comment by cocho-gore** [comment]
Ok, thanks I already created the new issue as recommended.
