### ISSUE TITLE
Unable to run spin in Getting started tutorial with Spinnaker

### ISSUE THREAD

**Issue by jaksky** [GoogleCloudPlatform/spinnaker-for-gcp#201]
Hello,
I am new to spinnaker and giving a try following tutorial where I got stuck on [running spin](https://cloud.google.com/solutions/continuous-delivery-spinnaker-kubernetes-engine#create_the_deployment_pipeline) and creating application via spin. I am not able to resolve this.
I have configured spinnaker with public access via IAP but I am not able to run spin neither with port-forward to gate service nor over my public url.
I either get: 
```
with port forward:  kubectl port-forward --namespace spinnaker $(kubectl get pod --namespace spinnaker --selector="app=spin,cluster=spin-gate" --output jsonpath='{.items[0].metadata.name}') 8080:8084
spin application list --gate-endpoint http://localhost:8080
Could not reach Gate, please ensure it is running. Failing.
403 
```
Or accessing over public URL I am crashing the app
```
panic: interface conversion: interface {} is nil, not string
goroutine 1 [running]:
github.com/spinnaker/spin/cmd/orca-tasks.idFromTaskRef(0x0, 0x0, 0x0)
        /var/lib/jenkins/workspace/Build_PrimaryArtifacts/build_input/build_spin/spin/cmd/orca-tasks/task_watcher.go:80 +0xf7
github.com/spinnaker/spin/cmd/orca-tasks.WaitForSuccessfulTask(0xc00010fab0, 0x0, 0x5, 0x97a280, 0xc00050eb10)
        /var/lib/jenkins/workspace/Build_PrimaryArtifacts/build_input/build_spin/spin/cmd/orca-tasks/task_watcher.go:27 +0x40
github.com/spinnaker/spin/cmd/application.saveApplication(0xc00011fb80, 0xc0000a2900, 0x0, 0x0)
        /var/lib/jenkins/workspace/Build_PrimaryArtifacts/build_input/build_spin/spin/cmd/application/save.go:111 +0x510
github.com/spinnaker/spin/cmd/application.NewSaveCmd.func1(0xc00011fb80, 0xc0000ee400, 0x0, 0x8, 0x0, 0x0)
        /var/lib/jenkins/workspace/Build_PrimaryArtifacts/build_input/build_spin/spin/cmd/application/save.go:50 +0x34
github.com/spf13/cobra.(*Command).execute(0xc00011fb80, 0xc0000ee300, 0x8, 0x8, 0xc00011fb80, 0xc0000ee300)
        /var/lib/jenkins/workspace/Build_PrimaryArtifacts/build_input/build_spin/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
```

I am unable to find root cause, can someone help?

**Comment by jaksky** [comment]
Issue caused by spinnaker Service account is not added to IAP as a Web User. That SA is added as authorisation account for spin
